//app
export const APP_GET_USER_INFO = 'APP_GET_USER_INFO';
export const APP_CHANGE_CLIENT_HEIGHT = 'APP_CHANGE_CLIENT_HEIGHT';
export const APP_PROBLEM_SHOW = 'APP_PROBLEM_SHOW';//
export const APP_PUT_PROBLEM = 'APP_PUT_PROBLEM';//发送问题
export const APP_CHANGE_LEFTMENU_SELECTED = 'APP_CHANGE_LEFTMENU_SELECTED';

// 我的申请
export const CHANGE_BUDGET_APPLICATION_KEY_VALUE = 'CHANGE_BUDGET_APPLICATION_KEY_VALUE';//修改我的申请的key,value
export const CHANGE_BUDGET_ADJUST_APPLICATION_KEY_VALUE = 'CHANGE_BUDGET_ADJUST_APPLICATION_KEY_VALUE';//修改我的调整申请的key,value
export const CHANGE_BUDGET_APP_OR_ADJUST_DETAIL_KEY_VALUE = 'CHANGE_BUDGET_APP_OR_ADJUST_DETAIL_KEY_VALUE';//修改我的调整申请的key,value
export const CHANGE_BUDGET_APP_OR_ADJUST_EDIT_KEY_VALUE = 'CHANGE_BUDGET_APP_OR_ADJUST_EDIT_KEY_VALUE';//修改我的调整申请的key,value
// export const GET_BUDGET_APPLICATION_DEFINE = 'GET_BUDGET_APPLICATION_DEFINE';//获取单据类型定义
// export const GET_BUDGET_APPLICATION_TYPE_LIST = 'GET_BUDGET_APPLICATION_TYPE_LIST';//获取单据类型列表


//预算单据待审批
export const BUDGET_CHANGE_SHOW_OR_HIDE = 'BUDGET_CHANGE_SHOW_OR_HIDE';//修改待审批高级条件页面是否展示
export const CHANGE_BUDGET_UNAPPROVED_KEY_VALUE = 'CHANGE_BUDGET_UNAPPROVED_KEY_VALUE';//修改我的申请的key,value

//预算单据已审批
export const CHANGE_BUDGET_APPROVED_KEY_VALUE = 'CHANGE_BUDGET_APPROVED_KEY_VALUE';//修改我的申请的key,value
export const BUDGET_CHANGE_APPROVED_SHOW_OR_HIDE = 'BUDGET_CHANGE_APPROVED_SHOW_OR_HIDE';//修改已审批高级条件页面是否展示
export const BUDGET_CHANGE_APPROVED_TABS_INDEX = 'BUDGET_CHANGE_APPROVED_TABS_INDEX';//修改tab切换的下标